Dev branch
pollyBe/blogfolio2.0 pull request #1
Opened 2024-12-11 16:02 UTC by pollyBe

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/ui-components/Person/Person.tsx
> +  // const [authorized, setAuthorized] = useState(false)
remove commented code

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/ui-components/Title/Title.tsx
> +  children: React.ReactNode,
it is better use string variables

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/ui-components/BurgerMenu/BurgerMenu.tsx
> +  console.log('is active', isActive)
remove console.log

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/ui-components/BurgerMenu/BurgerMenu.tsx
> +    <button onClick={() => dispatch(switchIsActive(isActive? false:true))} className={style.burgerBtn}>
You can use button from components

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/ui-components/Input/Input.tsx
> +      />
add error text

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/Components/Footer/Footer.tsx
> +        <p>©2022 Blogfolio</p>
use Data to calculate year

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/Components/Header/Header.tsx
> +// import { useState } from "react";
remove comment

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/Components/Tabs/TabList/TabList.tsx
> +  const tabs: string[] = ["All", "My Favourites", "Popular"];
it is a props

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/Components/Tabs/TabContent/TabContent.tsx
> +useEffect(() => {
This is a universal component; it should not contain business logic inside it.

2024-12-17 19:56 UTC, PavelYermakov1 commented on my-first-app/src/Components/SignUpForm/SignUpForm.tsx
> +  console.log(formValue);
remove console

2024-12-30 16:07 UTC, pollyBe commented
@Mukhamed-Talaspaev

2024-12-30 22:27 UTC, Mukhamed-Talaspaev requested changes

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/README.md
rewrite readme file

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +import style from './PostCard.module.scss'
style is object and if you have a lot classes which are used in your component you can destructure it 
as example
  const { infoWrap, cardWrap, date } = styles;

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +    case 'sizeL':
inside in PostCard folder for each rendering case create seperated components.example: sizeLcomponent,SizeMcomponent and use them here

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +      </div>
create a separate component likebtngroup

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +    </div>
use likebtngroup

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +        </div>
use likebtngroup

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +          </div>
use likebtngroup

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/SelectedPost/SelectedPost.tsx
> +            </div>
use likebtngroup

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Components/SignInForm/SignInForm.tsx
> +      <a className={style.link} href='#'>Forgot password?</a>
create link which redirect to reset password page 
/auth/users/reset_password/

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Context/Context.tsx
> +export const ThemeContext = createContext<IThemeContext | null>(null);
try to transfer this to the store as a slice

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Pages/About/About.tsx
> +export default About
add something about you or just delete this page

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Pages/Layout/Layout.tsx
> +    >
comment about transferring to the store

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/Pages/MyPosts/myPosts.tsx
> +export default MyPosts;
add code in mypost page

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/index.css
> +} */
remove comments

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/store/index.ts
> +  },
remove thunk if you don't use it

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/ui-components/Person/Person.tsx
> +// import { NavLink } from "react-router-dom"
remove it

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/src/ui-components/Person/Person.tsx
> +  // console.log(userInfo.username)
remove it

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/tsconfig.node.tsbuildinfo
> +{"fileNames":["./node_modules/typescript/lib/lib.d.ts","./node_modules/typescript/lib/lib.es5.d.ts","./node_modules/typescript/lib/lib.dom.d.ts","./node_modules/typescript/lib/lib.webworker.importscr
add it in gitignore

2024-12-30 22:27 UTC, Mukhamed-Talaspaev commented on my-first-app/tsconfig.tsbuildinfo
> +{"root":["./src/app.tsx","./src/main.tsx","./src/vite-env.d.ts","./src/components/button/button.tsx","./src/components/header/header.tsx","./src/components/input/input.tsx","./src/components/navbar/n
add it in gitignore

2025-01-06 21:13 UTC, pollyBe commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +        </div>
done

2025-01-06 21:14 UTC, pollyBe commented on my-first-app/src/Components/PostCard/PostCard.tsx
> +      </div>
done

2025-01-13 16:31 UTC, pollyBe commented on my-first-app/src/Components/Tabs/TabList/TabList.tsx
> +  const tabs: string[] = ["All", "My Favourites", "Popular"];
I tried, but everything goes wrong. i think i need to rewrite whole part with tabs in app.

2025-01-14 18:01 UTC, pollyBe commented on my-first-app/src/Pages/Layout/Layout.tsx
> +    >
forgot about this. fixed

2025-01-14 18:12 UTC, pollyBe commented on my-first-app/src/ui-components/BurgerMenu/BurgerMenu.tsx
> +    <button onClick={() => dispatch(switchIsActive(isActive? false:true))} className={style.burgerBtn}>
I tryed, but in that case i need to change a lot in button component and add changes in all components that are using Button. Cani leave it like this?

2025-01-14 20:14 UTC, PavelYermakov1 approved these changes

2025-01-14 20:15 UTC, merged